// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend_D_D.Data;

#nullable disable

namespace backend_D_D.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20240902143049_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend_D_D.Models.Entity.Backgound", b =>
                {
                    b.Property<int>("BackgroundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BackgroundId"));

                    b.Property<int>("Difetti")
                        .HasColumnType("int");

                    b.Property<int>("Ideali")
                        .HasColumnType("int");

                    b.Property<int>("Legami")
                        .HasColumnType("int");

                    b.Property<int>("PersonaggioID")
                        .HasColumnType("int");

                    b.Property<int>("TrattiCaratteriali")
                        .HasColumnType("int");

                    b.HasKey("BackgroundId");

                    b.ToTable("Backgound");
                });

            modelBuilder.Entity("backend_D_D.Models.Entity.Classi", b =>
                {
                    b.Property<int>("ClassiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassiId"));

                    b.Property<int>("Livello")
                        .HasColumnType("int");

                    b.Property<int>("PersonaggioID")
                        .HasColumnType("int");

                    b.HasKey("ClassiId");

                    b.ToTable("Classi");
                });

            modelBuilder.Entity("backend_D_D.Models.Entity.Personaggio", b =>
                {
                    b.Property<int>("PersonaggioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonaggioID"));

                    b.Property<int>("Allineamento")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<int>("IdUtente")
                        .HasColumnType("int");

                    b.HasKey("PersonaggioID");

                    b.ToTable("Personaggio");
                });
#pragma warning restore 612, 618
        }
    }
}
